### PR TITLE
Fix icons as of #8

### PR DESCRIPTION
**Pull request by prateekmedia**

### CODE REVIEW

**Comment by prateekmedia** [comment]
I can Merge it right away, just waiting for any reviews on code, otherwise I will merge it...

**Comment by prateekmedia** [comment]
Ok The code seems to work, merging in main branch

**Comment by m0hithreddy** [comment]
Hey, sorry I will be working in the morning. Yes, the code seems to (almost) work. Almost because it is too keen to observe and I know that it is bound to happen. In the case where the up and down speed units are mismatching particularly when B/s and any other the difference is clear, like in the photo shown.
Screenshot from 2020-11-26 21-16-02

You can see the boundaries aren't clear. Again the reason is the same, variable character width (non-monospaced font). But I understand it is too small to care about. But if you want to take care we need to create another component for units, it is overkill though.

And regarding font, It is surprising that courier new isn't there, I kind of thought it is a basic font, and if in the future you consider using a monospace font, you can simply give monospace for font-family attribute and the system selects one.

Thanks & Regards.

**Comment by prateekmedia** [comment]
@m0hithreddy you are right, but now this is the only working solution, also note that B/s is not too common to occur most of the time it will be KB/s or high , yes Monospace is available in Manjaro too , will think over font family.

I think you have installed font-microsoft-ttf or something similar cause it's a microsoft font.

**Pull request merged**
