### PR TITLE
added fixed width, icons to the right and text align to left options

### PR DESCRIPTION
**Pull request by fluoroom**
Tested on GNOME 40 and everything works, should work everywhere.
Sorry i accidentally applied a formatter before editing and now almost every line is different :/

### CODE REVIEW

**Comment by prateekmedia** [comment]
Why? Minimum width is just fine then why do you want fixed width? Also have you done other changes from that cause I can also see some variables are removed from prefs.js ?

**Comment by fluoroom** [comment]
Fixed width was my first addition and was my attempt to shrink space, then i realized it was a matter of padding in components themselves. I agree on not including fixed width to keep it simple. (i can redo this pull request if you want)
I've not done other changes nor removed any variables to prefs.js, i've indeed added some, but not changed anything else.

**Comment by prateekmedia** [comment]
OK remove the fixed width part when you are free. The alignment seems legit
and also why have you removed systemcolor parameter from schemas. I see it
removed in changes.

**Comment by prateekmedia** [comment]
OK remove the fixed width part when you are free. The alignment seems legit and also why have you removed systemcolor parameter from schemas. I see it removed in changes.

**Comment by fluoroom** [comment]
Ok, then i'll redo with fixed width removed.
systemcolor removal was probably me hitting Ctrl+X instead of C when copying the boolean declaration, my bad

**Pull request closed without merging**
