### PR TITLE
Reserve space for each component v0

### PR DESCRIPTION
**Pull request by m0hithreddy**
Unless you have some serious problems with the courier new font this should look fine. And cases where no network activity is there isn't addressed since it is a personal preference you can decide on it.

### CODE REVIEW

**Comment by prateekmedia** [comment]
Will see this or any alternative for it, or will find a way to do it without changing font or if its last then will have to add an option on preferences.

Nice work btw

**Comment by m0hithreddy** [comment]
Well I can think of other way but at a cost of having the units as separate components as we were having us, ds, ts, td.

**Comment by prateekmedia** [comment]
That will only increase the complexity , 
below is the link that is from linux mint applet they have done it without changing font, although I can't understand their version of Javascript , Ahm. But if you could then please give it a try....
 https://cinnamon-spices.linuxmint.com/files/applets/download-and-upload-speed@cardsurf.zip

It has all features this extension have + many many more...

**Comment by prateekmedia** [comment]
Looks like It is good to create another 4 indicators for 4 icons, and marking other labels as text align right

**Comment by prateekmedia** [comment]
Try to made it fix as you said by making other indicators for icon, 

I am also not considering this PR cause Courier New font is not one the one that comes with every linux distro like in Manjaro, and they require you to install it separately which is not a good thing.

**Pull request closed without merging**
